name: App Release

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}

      # Generate app keystore
      - name: Generate app keystore
        run: |
          mkdir -p app/
          echo "${{ secrets.JKS_BASE64 }}" | base64 -d > app/keystore

      - name: Build
        run: ./gradlew assembleFreeRelease

      - uses: actions/upload-artifact@v4
        with:
          name: app-free-release.apk
          path: app/build/outputs/apk/free/release/app-free-release.apk
